angular.json
Changed the config to use ESBuild, a much faster build system than the current Angular one:
https://angular.io/guide/esbuild
=> DEMO-341 (build): Switched to ESBuild compiler

angular.json, src/app/app.component.html, src/app/app.component.ts, src/app/global-status-bar/global-status-bar.component.ts, src/app/main/main.component.ts, src/app/scenario-data-display/scenario-data-display.component.ts, src/app/scenario-library/scenario-library.component.ts, src/index.html
Just switched from the default selector prefix of 'app' to the project-specific one 'fds'
=> Switched 'app' selector to 'fds'

src/app/main/main.component.css, src/app/main/main.component.html, src/app/main/output-data-display/output-data-display.component.css, src/app/main/output-data-display/output-data-display.component.html, src/app/main/output-data-display/output-data-display.component.ts, src/app/main/output-data-display/view-graph/view-graph.component.html, src/app/main/output-data-display/view-graph/view-graph.component.ts, src/app/main/output-data-display/view-table/view-table.component.html, src/app/main/output-data-display/view-table/view-table.component.ts, src/app/shared/child-container/child-container.component.css, src/app/shared/child-container/child-container.component.html, src/styles.css
**JIRA Ticket [DEMO-345](https://rocketcom.atlassian.net/browse/DEMO-345)**
This pr adds a tabs, notification, deviations, and view headers/sub-headers. I came up with a design which I felt looks okay using the astro child-container figma with the blue border below the tabs and notification. I'd like to see what @FMorrison87 comes up with for a design and then we can just go with what we all think looks best until design can have a look.
Here is the section the pr addresses
=> DEMO-345 (feat): Create Child Header and Sub Headers

package-lock.json, package.json, src/app/app.component.spec.ts, src/app/global-status-bar/global-status-bar.component.ts, src/app/main/main.component.ts, src/app/scenario-library/scenario-library.component.ts, src/app/shared/units/unit-conversions.ts, src/app/store/app.actions.ts, src/app/store/app.model.ts, src/app/store/app.reducer.ts, src/app/store/app.selectors.ts, src/index.html, src/main.ts
**JIRA Ticket [DEMO-342](https://rocketcom.atlassian.net/browse/DEMO-342)**
Installs NgRx to use for global state management. Creates a featureGroup to hold satellites state. Also adds a selector to retrieve satellites state and the selectedSatellite by catalog id.
This is only the initial implementation. Future construction of state to match correct data schema needed. I choose not to add ngrx/effects at this time to reduce complexity and ease the learning curve of this tool. 
- [N/A] Handles responsiveness as required
- [N/A] Dark theme styles are correct
- [N/A] Light theme styles are correct
=> DEMO-342 (feat): Setup NgRx

src/app/main/main.component.css
Bug fix on main component height to enable proper overflow behavior.
**JIRA Ticket [Jira Issue Key](ticketURL)**
=> Bugfix(main-component): Add Height To Contain Main Component Properly

src/app/main/utility-components/log-utility/log-utility.component.css, src/app/main/utility-components/log-utility/log-utility.component.html, src/app/main/utility-components/log-utility/log-utility.component.ts
**JIRA Ticket [Log Utility Updates](https://rocketcom.atlassian.net/browse/DEMO-370)**
- Remove tabs
- Remove controls and "more options" buttons
-
=> DEMO 370 (chore): Log Utility Updates

src/app/+store/app.actions.ts, src/app/+store/app.adapters.ts, src/app/+store/app.effects.ts, src/app/+store/app.model.ts, src/app/+store/app.reducer.ts, src/app/+store/app.selectors.ts, src/app/app.component.ts, src/app/main/main.component.ts, src/app/mock-data/generate-data.ts, src/app/scenario-library/scenario-library.component.html, src/app/scenario-library/scenario-library.component.ts
Just merging into France's data branch
Entities!
=> Km.state entity conversions

src/app/main/utility-components/track-data-utility/track-data/track-data.component.css, src/app/main/utility-components/track-data-utility/track-data/track-data.component.html, src/app/main/utility-components/track-data-utility/track-data/track-data.component.ts
**JIRA Ticket [Custom Legend](https://rocketcom.atlassian.net/browse/DEMO-390**
- Build custom legend - colors for checkboxes are not assigned yet since data will be changing
- Legend had to be custom built due to inability/complexity to have access to functions on checkboxes. With this- absolute positioning was the only way to get the legend 'inside' the chart canvas. This makes responsiveness tricky- but it is responsive to the drawers opening/closing.
=> DEMO- 390 (feature): Custom legend

src/app/core/scenario-data-display/scenario-data-display.component.html, src/app/core/scenario-data-display/scenario-data-display.component.ts, src/app/shared/units/unit-selector.component.html
**JIRA Ticket [Post Audit - Scenario Properties](https://rocketcom.atlassian.net/browse/DEMO-397)**
- Change icon 
- Add spacecraft name to properties header
=> DEMO 397 (chore): Scenario Properties

src/app/core/global-status-bar/global-status-bar.component.css, src/app/core/global-status-bar/global-status-bar.component.html
**JIRA Ticket [Post Audit - GSB](https://rocketcom.atlassian.net/browse/DEMO-380)**
- Remove tabs
- Remove third monitoring icon
- Change second icon to match figma
=> DEMO-380(chore): GSB updates

.gitignore, src/app/app.component.ts, src/app/core/scenario-data-display/scenario-data-display.component.ts, src/app/main/inputs-outputs/inputs/inputs.component.ts, src/app/main/output-data-display/output-data-display.service.ts, src/app/main/utility-components/propagator-utility/view-orbit/view-orbit-table.service.ts
Just a small PR to clean up the subscriptions in the app. If they don't get cleaned up, there's memory leaks
- [] Works in Chrome
=> Added subscription cleanup

src/app/+state/app.adapters.ts, src/app/+state/app.effects.ts, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/core/scenario-data-display/scenario-data-display.component.ts, src/app/guards/valid-spacecraft.guard.ts, src/app/main/utility-components/propagator-utility/input-source/input-source.component.spec.ts, src/app/main/utility-components/propagator-utility/propagator-controls/propagator-controls.component.spec.ts, src/app/main/utility-components/propagator-utility/view-orbit/view-model/view-model.component.spec.ts, src/app/main/utility-components/propagator-utility/view-orbit/view-orbit.component.spec.ts, src/app/main/utility-components/propagator-utility/view-orbit/view-table/view-table.component.spec.ts, src/app/main/utility-components/track-data-utility/dummy-file-data.ts, src/app/main/utility-components/track-data-utility/track-data-utility.component.ts, src/app/main/utility-components/track-data-utility/track-data/settings/settings.component.css, src/app/main/utility-components/track-data-utility/track-data/settings/settings.component.spec.ts, src/app/main/utility-components/track-data-utility/track-data/settings/settings.component.ts, src/app/main/utility-components/track-data-utility/track-data/sites/sites.component.css, src/app/main/utility-components/track-data-utility/track-data/sites/sites.component.spec.ts, src/app/main/utility-components/track-data-utility/track-data/track-data.component.css, src/app/main/utility-components/track-data-utility/track-data/track-data.component.spec.ts, src/app/main/utility-components/track-data-utility/track-data/track-data.component.ts, src/app/main/utility-components/track-data-utility/track-files/track-files.component.spec.ts, src/index.html
**JIRA Ticket [Jira Issue Key](ticketURL)**
I added a full prettier format after fixing the errors but the fix is in the first commit
=> fix: address takeUntilDestroyed errors

src/app/app.component.ts, src/app/core/scenario-data-display/scenario-data-display.component.ts
Moved subscriptions to constructors; got rid of extra lifecycle methods
=> Fixed cleanup

src/app/main/inputs-outputs/inputs/inputs.component.html, src/app/main/inputs-outputs/inputs/inputs.component.ts
**JIRA Ticket [Replace popup menu with select](https://rocketcom.atlassian.net/browse/DEMO-420)**
- Remove popup/type ahead functionality and replace with select menu for database file
=> DEMO-420 (chore): Replace popup menu with select

src/app/main/utility-components/track-data-utility/track-data/track-data-graph/track-data-graph.component.html, src/app/main/utility-components/track-data-utility/track-data/track-data-graph/track-data-graph.component.ts, src/app/main/utility-components/track-data-utility/track-data/track-data.component.ts, src/app/main/utility-components/track-data-utility/track-files-table.service.ts, src/app/main/utility-components/track-data-utility/track-files/track-files.component.ts
merging some changes from Maria's branch into mine
=> ordered dates, updates legened, attempted table service data usage

src/app/app-routing.ts
@micahjones13 This will lazy-load your cesium stuff, which splits that huge bundle into basically thirds. It won't fix that budget issue because cesium is still huge, but each part will be much smaller
=> Lazy load cesium-using route

src/app/main/output-data-display/output-data-display.component.html, src/app/main/output-data-display/output-data-display.model.ts, src/app/main/output-data-display/output-data-display.service.ts, src/app/main/output-data-display/solution-table/solution-table.component.html, src/app/main/output-data-display/solution-table/solution-table.component.ts
[demo-430](https://rocketcom.atlassian.net/browse/DEMO-430)
Refactored the OD Solutions table so that it reinitialized with new data every time it receives no SolutionsData. I mostly used the same methods as OD Performance.
Additionally I minority modified the OD Service to that it clears solutionData before pushing a new set of data onto it. Previously it wasn't which was causing the slowdown Frances was experiencing since the app never cleared old rows and instead attempted to render hundreds of rows over the course of the app running.
=> DEMO-430 OD Solutions data update

src/app/app.component.css, src/app/main/utility-components/track-data-utility/track-files/track-files.component.css
The header was taking up way too much space. I made adjustments.
=> fix(header): header padding fix

src/app/main/inputs-outputs/inputs-outputs.component.ts, src/app/main/output-data-display/output-data-display.component.ts, src/app/main/output-data-display/output-data-display.service.ts
This PR fixes an observable issue with the determine orbit banner where it would turn on or off depending on the click and then get into a weird state where it would flicker.
=> fix(inputs): fixing determine orbit banner

src/app/main/inputs-outputs/inputs-outputs.component.css, src/app/main/output-data-display/output-data-display.component.css, src/app/main/output-data-display/output-data-display.component.html, src/app/shared/custom-segmented-button/custom-segmented-button.component.css, src/app/shared/custom-segmented-button/custom-segmented-button.component.html
This PR rolls up three tickets worth of minor UI fixes:
- The orbit determination button was cutoff
- The graph in the main screen of the app was cutoff
- the toggle buttons in the main part of the app (graph | table, create TLE) were mis-aligned
=> fix(ui): minor UI issues
